Repository AY2122S2-CS2103T-W15-1/tp, pull requests merged in 2022-03, with the labels that each got.

#84 Branch add test date applied
  src/test/java/seedu/address/model/applicant/DateAppliedTest.java
Labels: test

#88 Fix a constructor error in QualificationTest
  src/test/java/seedu/address/model/applicant/QualificationTest.java
Labels: test

#119 Edit DG for EditApplicant implementation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditApplicantActivityDiagram.puml
  docs/diagrams/EditApplicantSequenceDiagram.puml
  docs/diagrams/EditApplicantState1.puml
  docs/diagrams/EditApplicantState2.puml
  docs/diagrams/EditApplicantState3.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/images/EditApplicantActivityDiagram.png
  docs/images/EditApplicantSequenceDiagram.png
  docs/images/EditApplicantState1.png
  docs/images/EditApplicantState2.png
  docs/images/EditApplicantState3.png
  docs/team/ro4k9.md
  src/main/java/seedu/address/logic/commands/applicant/EditApplicant.java
  src/main/java/seedu/address/logic/parser/applicant/EditApplicantParser.java
Labels: documentation

#127 Update DG for implementation for EditApplicant
  docs/diagrams/EditApplicantSequenceDiagram.puml
  docs/images/EditApplicantSequenceDiagram.png
Labels: documentation

#140 Edit EditApplicant
  src/main/java/seedu/address/logic/commands/applicant/EditApplicant.java
Labels: bug

#153 Fix bug in mark job
  src/main/java/seedu/address/logic/commands/job/MarkJob.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/job/MarkJobParser.java
Labels: bug
